### ISSUE TITLE
it's ignoring the options

### ISSUE THREAD

**Issue by Sigfried** [bartlomiejzuber/use-open-window#313]
No matter how I change the options, the same size window gets opened.

```javascript
const WINDOW_OPEN_OPTIONS = {
  centered: true, /* default */
  spec: {
    width: 100, /* window width */
    height: 900, /* window height */
  },
  // transform: 'scale(0.8)',
  top: 20,
  left: window.innerWidth - 250,
};
function HelpButton(props) {
  const {doc, windowOptions} = props;
  // const options = windowOptions ?? WINDOW_OPEN_OPTIONS;
  const options = WINDOW_OPEN_OPTIONS;
  const url = `/help?doc=${doc}`;
  const [handleWindowOpen, newWindowHandle] = useOpenInWindow(url, options);
  console.log({newWindowHandle});
  if (doc === 'legend') {
    return <Button onClick={ev=>handleWindowOpen(ev,options)}>Show legend</Button>;
  }
}
```

**Comment by Sigfried** [comment]
Whoops...I was passing options in both ways in that example. But passing through hook by itself wasn't working. Will keep playing with it.

**Comment by Sigfried** [comment]
Ok, here's passing through callback:
![image](https://user-images.githubusercontent.com/1586931/224150183-8e99e8ad-a3ae-4f00-bf78-81b64fbdfef1.png)


And here's passing through hook:
![image](https://user-images.githubusercontent.com/1586931/224150971-e5f2c837-f4c8-45ed-86d9-4a9901d23323.png)


And I just noticed that I had left `centered: true` in the options even though I was trying to position it elsewhere, but deleting that didn't make a difference.

**Comment by bartlomiejzuber** [comment]
Hey, thanks for raising that! That's in fact a typo in the demo script code. You'd should pass `specs` not `spec`.
Sorry about that and once again thanks for spotting! I'll push fix for that in couple minutes. :)

**Comment by bartlomiejzuber** [comment]
Ok demo page has been just updated https://use-open-window-demo.netlify.app/.

I'd recommend to use `tsc` as this small lib also provides types so can catch such issues. :)
