### ISSUE TITLE
addEventListener

### ISSUE THREAD

**Issue by chriskolenko** [bartlomiejzuber/use-open-window#316]
Hi all, 

How can I add an event listener so I can get data back from the child window.

Usecase;
I want to have an OpenID flow running in a window so I can pass back the User ID to a form in the parent.

**Comment by bartlomiejzuber** [comment]
Hi @chriskolenko , 

That sort of communication is out of the scope of this lib.
To do that I'd say you should use `window.postMessage` , you'll can get the reference of the parent with:
```javascript
targetWindow = window.opener
```

, and then dispatch a [MessageEvent](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent) on it with targetWindow.postMessage().
